create-image:
	docker build -t react-typescript-starter .

run-image:
	docker run -it --rm -p 3000:3000 --name react-typescript-ui react-typescript-starter

run-image-dev:
	docker run -it --rm -p 3000:3000 -v ${PWD}:/app react-typescript-starter
# Path: react-typescript-starter/Makefile

